drm/i915: ensure oa config uuid is null terminated
Because dev_priv is 0-ed it's not currently an issue, but since we
have dev_priv->perf.oa.test_config.uuid size at uuid + 1, we could
just copy the null character.

v2: Use strlcpy instead of strncpy (Chris)

Signed-off-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
Cc: Rodrigo Vivi <rodrigo.vivi@intel.com>
Reviewed-by: Chris Wilson <chris@chris-wilson.co.uk>
Link: https://patchwork.freedesktop.org/patch/msgid/20171102121827.436-1-lionel.g.landwerlin@intel.com

v3: cherry-pick to fix compile warnings for string truncation as:

i915_oa_hsw.c: In function ‘i915_perf_load_test_config_hsw’:
i915_oa_hsw.c:116:2: error: ‘strncpy’ output truncated before terminating nul copying 36 bytes from a string of the same length [-Werror=stringop-truncation]

 Conflicts:
	drivers/gpu/drm/i915/i915_oa_cflgt2.c
Signed-off-by: Xinyun Liu <xinyun.liu@intel.com>